In [1]:
from dis import dis
from turtle import speed
import pygame
import sys
import math

pygame.init()

display = pygame.display.set_mode((800,600))
clock = pygame.time.Clock()

class Player:
    '''
    player setting
    '''
    def __init__(self, x, y, width, height, health):
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.health = health
    def main(self, display):
        pygame.draw.rect(display, (255,0,0), (self.x, self.y, self.width, self.height))



class Enemy:
    '''
    Enemy setting
    '''
    def __init__(self, x, y, width, height, health):
        self.x = x
        self.y = y
        self.speed = 2
        self.width = width
        self.height = height
        self.health = health
    def main(self, display, player):
        pygame.draw.rect(display, (0,0,255), (display_scroll[0], display_scroll[1], self.width, self.height))



class PlayerBullet:
    '''
    Player bullet(attack)
    '''
    def __init__(self, x, y, mouse_x, mouse_y):
        self.x = x
        self.y = y
        self.mouse_x = mouse_x
        self.mouse_y = mouse_y
        self.speed = 15
        self.angle = math.atan2(y-mouse_y, x-mouse_x)
        self.x_vel = self.speed * math.cos(self.angle)
        self.y_vel = self.speed * math.sin(self.angle)
    def main(self, display):
        self.x -= int(self.x_vel)
        self.y -= int(self.y_vel)

        pygame.draw.circle(display, (0,0,0), (self.x, self.y), 5)

player = Player(400,300,32,32,120)      #x,y,width, height, health

enemy = Enemy(400,30,32,32,10)

display_scroll = [0,0]

player_bullets = []

while True: 
    display.fill((24,186,32))
    
    pygame.draw.rect(display, (255,0,0),(10,10, 250,5))
    pygame.draw.rect(display, (0,255,0),(10,10, player.health,5))

    mouse_x, mouse_y = pygame.mouse.get_pos()

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            sys.exit()
            pygame.QUIT
        
        if event.type == pygame.MOUSEBUTTONDOWN:
            if event.button == 1:
                player_bullets.append(PlayerBullet((player.x*2+player.width)/2, (player.y*2+player.height)/2, mouse_x, mouse_y))

    keys = pygame.key.get_pressed()

    pygame.draw.rect(display, (255,255,255),(100-display_scroll[0],100-display_scroll[1],16,16))

    if keys[pygame.K_a]:
        display_scroll[0] -= 5

        for bullet in player_bullets:
            bullet.x += 5
    if keys[pygame.K_d]:
        display_scroll[0] += 5

        for bullet in player_bullets:
            bullet.x -= 5
    if keys[pygame.K_w]:
        display_scroll[1] -= 5

        for bullet in player_bullets:
            bullet.y += 5
    if keys[pygame.K_s]:
        display_scroll[1] += 5

        for bullet in player_bullets:
            bullet.y -= 5

    player.main(display)
    enemy.main(display,player)

    for bullet in player_bullets:
        bullet.main(display)

    clock.tick(60)
    pygame.display.update()

pygame 2.1.2 (SDL 2.0.18, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


SystemExit: 

c:\Users\kland\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3445: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


: 

In [ ]:
x = 400 
y = 300 
mouse_x = 434
mouse_y = 268
speed = 15
angle = math.atan2(y-mouse_y, x-mouse_x)
x_vel =  math.cos(angle) * speed
y_vel = speed * math.sin(angle)
print(angle, x_vel,y_vel, type(angle), type(x_vel))

2.38648825011112 -10.922999890392045 10.280470485074863 <class 'float'> <class 'float'>


: 

In [1]:
class A:
    pass
a = A()


In [8]:
isinstance(a, type)

False

In [21]:
import collections
import pygame
a = pygame.sprite.Group()
a.add(pygame.sprite.Sprite())
a.add(pygame.sprite.Sprite())
isinstance(a, collections.Sequence)

False

In [37]:
a = 3
b = 2
for i in [a, b]:
    i += 3
a, b

(3, 2)

In [38]:
a = 3.0
b = 2.0
a // b

1.0

In [42]:
from copy import copy, deepcopy
import pygame
a = pygame.math.Vector2(1, 2)
b = a
c = copy(a)
d = deepcopy(a)
e = pygame.math.Vector2(a)

a.xy = (4, 3)
b, c, d, e

(<Vector2(4, 3)>, <Vector2(1, 2)>, <Vector2(1, 2)>, <Vector2(1, 2)>)

In [47]:
class A:
    def __init__(self):
        self.x = 3

class B(A):
    def __init__(self):
        super().__init__()
        self.y = 2

b = B()
b.x

3

In [54]:
a = pygame.math.Vector2(0, 0.0)
if a:
    print('ASFD')

In [62]:
a = pygame.math.Vector2(0, 2)
a.scale_to_length(0) if a else a
a

<Vector2(0, 0)>

In [6]:
import pygame
from pygame.locals import *

print(bin(FULLSCREEN))
print(bin(DOUBLEBUF))
print(bin(HWSURFACE))
print(bin(OPENGL))
print(bin(RESIZABLE))
print(bin(NOFRAME))
print(bin(SCALED))
print(bin(SHOWN))
print(bin(HIDDEN))

-0b10000000000000000000000000000000
0b1000000000000000000000000000000
0b1
0b10
0b10000
0b1000000000
0b1000000
0b10000000
0b100000


In [1]:
import pygame as pg
from pygame.locals import *

from OpenGL.GL import *
from OpenGL.GLU import *

cubeVertices = ((1,1,1),(1,1,-1),(1,-1,-1),(1,-1,1),(-1,1,1),(-1,-1,-1),(-1,-1,1),(-1,1,-1))
cubeEdges = ((0,1),(0,3),(0,4),(1,2),(1,7),(2,5),(2,3),(3,6),(4,6),(4,7),(5,6),(5,7))
cubeQuads = ((0,3,6,4),(2,5,6,3),(1,2,5,7),(1,0,4,7),(7,4,6,5),(2,3,0,1))

def wireCube():
    glBegin(GL_LINES)
    for cubeEdge in cubeEdges:
        for cubeVertex in cubeEdge:
            glVertex3fv(cubeVertices[cubeVertex])
    glEnd()

def solidCube():
    glBegin(GL_QUADS)
    for cubeQuad in cubeQuads:
        for cubeVertex in cubeQuad:
            glVertex3fv(cubeVertices[cubeVertex])
    glEnd()

def main():
    pg.init()
    display = (1680, 1050)
    pg.display.set_mode(display, DOUBLEBUF|OPENGL)

    gluPerspective(45, (display[0]/display[1]), 0.1, 50.0)

    glTranslatef(0.0, 0.0, -5)

    while True:
        for event in pg.event.get():
            if event.type == pg.QUIT:
                pg.quit()
                quit()

        glRotatef(1, 1, 1, 1)
        glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT)
        # solidCube()
        wireCube()
        pg.display.flip()
        pg.time.wait(10)

if __name__ == "__main__":
    main()

pygame 2.1.2 (SDL 2.0.18, Python 3.7.9)
Hello from the pygame community. https://www.pygame.org/contribute.html


GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glRotatef,
	cArguments = (1, 1, 1, 1)
)

: 

In [5]:
import Box2D

b = Box2D.b2ContactManager()


<bound method b2ContactManager_AddPair of b2ContactManager(allocator=None,
                 broadPhase=proxyCount=0,),
                 contactCount=0,
                 contactFilter=b2ContactFilter(),
                 contactList=None,
                 contactListener=b2ContactListener(),
                 )>

In [ ]:
import moderngl

In [2]:
class A:
    _a = []
    for i in range(100):
        _a.append(i)

In [3]:
A._a

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [11]:


class Bar(object):

    def __init__(self, x):
        self.x = x

    def called_class():
        print ("Class assignment")
        return 2
    
    y = called_class()

## "Class assignment"

def called_instance():
    print ("Instance assignment")
    return 2

class Foo(object):
    def __init__(self, x):
        self.y = called_instance()
        self.x = x

Bar(1)
Bar(2)
Foo(1)
## "Instance assignment"
Foo(2)
## "Instance assignment"

Class assignment
Instance assignment
Instance assignment


In [ ]:
import Box2D
Box2D.b2Body().conta

In [ ]:
Box2D.Box2D.b2ContactEdge().contact
Box2D.Box2D.b2Contact().

In [5]:
Box2D.b2FixtureDef()

b2FixtureDef(categoryBits=1,
             density=0.0,
             filter=categoryBits=1,groupIndex=0,maskBits=65535,),
             friction=0.20000000298023224,
             groupIndex=0,
             isSensor=False,
             maskBits=65535,
             restitution=0.0,
             shape=None,
             userData=None,
             )

In [16]:
import Box2D
Box2D.b2FixtureDef(density=1.0, shape=Box2D.b2PolygonShape(), categoryBits=0xFFFF)

b2FixtureDef(categoryBits=65535,
             density=1.0,
             filter=categoryBits=65535,groupIndex=0,maskBits=65535,),
             friction=0.20000000298023224,
             groupIndex=0,
             isSensor=False,
             maskBits=65535,
             restitution=0.0,
             shape=b2PolygonShape(vertices: []),
             userData=None,
             )

In [37]:
Box2D.b2Vec2().

b2Vec2(0,0)

In [44]:
import pygame
a = pygame.math.Vector2(3, 2)
pygame.math.Vector2().angle_to(a)

33.690067525979785

In [53]:
class A:
    a = 3

a = [A() for i in range(2)]


In [54]:
b = A()
b.a = 42
a.append(b)
b

In [55]:
print(a)

[<__main__.A object at 0x0000028F01566A48>, <__main__.A object at 0x0000028F01566B88>, <__main__.A object at 0x0000028F0153E7C8>]


In [56]:
del b

In [57]:
print(a)

[<__main__.A object at 0x0000028F01566A48>, <__main__.A object at 0x0000028F01566B88>, <__main__.A object at 0x0000028F0153E7C8>]


In [60]:
b

NameError: name 'b' is not defined

In [61]:
a[2].a

42

In [ ]:
Box2D.Box2D.b2Transform().

In [4]:
import pygame

screen = pygame.display.set_mode((1, 1))
a = pygame.image.load('../test/graphics/pixil-frame-0.png').convert_alpha()


pygame.Surface

: 

In [5]:
a = int(input("asdf"))

In [54]:
import Box2D
import math
PPM = 20
def _get_ellipsis_vertices(cls, pos, size):
	precision = 8
	vertices = []
	rect_size = (32, 32)
	for i in range(precision):
		angle = math.pi * 2 / precision * i
		x = (math.cos(angle) * size[0] + pos[0]) * rect_size[0] / PPM
		y = (math.sin(angle) * size[1] + pos[1]) * rect_size[1] / PPM
		vertices.append(Box2D.b2Vec2(x, y))
	return vertices

fixture = Box2D.b2FixtureDef(
		density=100.0,
		shape=Box2D.b2PolygonShape(vertices=_get_ellipsis_vertices(None, (0, 0.3), (0.4, 0.2))),
	)

world = Box2D.b2World()
body = world.CreateDynamicBody(position=(0, 0))
body.CreateFixture(fixture)
body.fixedRotation = True

from pprint import pprint
# pprint(list(body.fixtures[0].__class__.__dict__.keys()))
body.fixtures[0].shape.centroid

b2Vec2(0,0.48)

In [48]:
from os import path
from glob import glob
{
    path.basename(sprite_path) : [image_path for image_path in glob(path.join(sprite_path, '*'))]
    for sprite_path in glob(path.join('..', 'assets', '*'))
}


{'bullet_idle': ['..\\assets\\bullet_idle\\0.png'],
 'player_idle': ['..\\assets\\player_idle\\0.png',
  '..\\assets\\player_idle\\1.png',
  '..\\assets\\player_idle\\2.png',
  '..\\assets\\player_idle\\3.png',
  '..\\assets\\player_idle\\4.png',
  '..\\assets\\player_idle\\5.png'],
 'player_run': ['..\\assets\\player_run\\0.png',
  '..\\assets\\player_run\\1.png',
  '..\\assets\\player_run\\2.png',
  '..\\assets\\player_run\\3.png',
  '..\\assets\\player_run\\4.png',
  '..\\assets\\player_run\\5.png',
  '..\\assets\\player_run\\6.png',
  '..\\assets\\player_run\\7.png'],
 'tree_idle': ['..\\assets\\tree_idle\\0.png']}

In [6]:
import json
from os import path
p = path.join('..', 'assets', 'tree_idle', 'meta.json')
f = open(p)
f.close()
with open(p) as f:
    json_object = json.load(f)
json_object

{'x': 15, 'y': 24, 'l': 2, 't': 20, 'r': 29, 'b': 29}

In [9]:
import pathlib
json.loads(pathlib.Path('..', 'assets', 'tree_idle', 'meta.json').read_text())


{'x': 15, 'y': 24, 'l': 2, 't': 20, 'r': 29, 'b': 29}

In [14]:
from glob import glob
list(pathlib.Path('..', 'assets', 'tree_idle').glob('*'))

[WindowsPath('../assets/tree_idle/0.png'),
 WindowsPath('../assets/tree_idle/meta.json')]

In [ ]:
import pygame
import pathlib
pygame.display.init()
pygame.display.set_mode((1280, 720))
pygame.image.load(pathlib.Path('..', 'assets', 'tree_idle', '0.png')).convert_alpha()
pathlib.Path('..', 'assets', 'tree_idle', '0.png').name

In [2]:
import pathlib
pathlib.Path('..', 'assets', 'tree_idle', '0.png').name

'0.png'

In [18]:
import numpy as np
uv = np.array([
    [0, 0], [1, 0], [1, 1], [0, 1],
])
np.hstack([uv, uv]).flatten()

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1])

In [3]:
import Box2D
Box2D.b2Body.linearVelocity

In [7]:
a = None
print(a)

None


In [31]:
import numpy as np
import pygame
import Box2D
ndarray = np.array([3, 2, 1], dtype=np.float64)
pyvec = pygame.Vector3(2, 3, 1)
boxvec = Box2D.b2Vec3(2, 3, 1)
tup = (2, 2, 3)

In [69]:
class Vec3(np.ndarray):
    def __init__(self, x):
        super().__init__(x)

v = Vec3([13, 2, 1])

TypeError: object.__init__() takes exactly one argument (the instance to initialize)

In [72]:
import numpy as np
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
y = np.zeros(3, dtype=np.int32)
y

array([0, 0, 0])

In [86]:
np.add.reduce(x, 0, out=y)

array([ 9, 12, 15])

In [28]:
t = ('x', 'y')
''.join(t)

'xy'

In [31]:

from itertools import product
TABLE = {'x': 0, 'y': 1, 'z': 2, 'w': 3, 'r': 0, 'g': 1, 'b': 2, 'a': 3}

PROPERTY = [''.join(prod) for prod in product('x', repeat=1)]
PROPERTY += [''.join(prod) for prod in product('r', repeat=1)]
PROPERTY += [''.join(prod) for prod in product('xy', repeat=2)]
PROPERTY += [''.join(prod) for prod in product('rg', repeat=2)]
PROPERTY += [''.join(prod) for prod in product('xyz', repeat=3)]
PROPERTY += [''.join(prod) for prod in product('xyz', repeat=3)]
PROPERTY += [''.join(prod) for prod in product('xyzw', repeat=4)]
PROPERTY += [''.join(prod) for prod in product('rgba', repeat=4)]
print(list(PROPERTY))

['x', 'r', 'xx', 'xy', 'yx', 'yy', 'rr', 'rg', 'gr', 'gg', 'xxx', 'xxy', 'xxz', 'xyx', 'xyy', 'xyz', 'xzx', 'xzy', 'xzz', 'yxx', 'yxy', 'yxz', 'yyx', 'yyy', 'yyz', 'yzx', 'yzy', 'yzz', 'zxx', 'zxy', 'zxz', 'zyx', 'zyy', 'zyz', 'zzx', 'zzy', 'zzz', 'xxx', 'xxy', 'xxz', 'xyx', 'xyy', 'xyz', 'xzx', 'xzy', 'xzz', 'yxx', 'yxy', 'yxz', 'yyx', 'yyy', 'yyz', 'yzx', 'yzy', 'yzz', 'zxx', 'zxy', 'zxz', 'zyx', 'zyy', 'zyz', 'zzx', 'zzy', 'zzz', 'xxxx', 'xxxy', 'xxxz', 'xxxw', 'xxyx', 'xxyy', 'xxyz', 'xxyw', 'xxzx', 'xxzy', 'xxzz', 'xxzw', 'xxwx', 'xxwy', 'xxwz', 'xxww', 'xyxx', 'xyxy', 'xyxz', 'xyxw', 'xyyx', 'xyyy', 'xyyz', 'xyyw', 'xyzx', 'xyzy', 'xyzz', 'xyzw', 'xywx', 'xywy', 'xywz', 'xyww', 'xzxx', 'xzxy', 'xzxz', 'xzxw', 'xzyx', 'xzyy', 'xzyz', 'xzyw', 'xzzx', 'xzzy', 'xzzz', 'xzzw', 'xzwx', 'xzwy', 'xzwz', 'xzww', 'xwxx', 'xwxy', 'xwxz', 'xwxw', 'xwyx', 'xwyy', 'xwyz', 'xwyw', 'xwzx', 'xwzy', 'xwzz', 'xwzw', 'xwwx', 'xwwy', 'xwwz', 'xwww', 'yxxx', 'yxxy', 'yxxz', 'yxxw', 'yxyx', 'yxyy', 'yx

In [37]:
import numpy as np
from multipledispatch import dispatch
from numbers import Number
from typing import Any
from itertools import product
TABLE = {'x': 0, 'y': 1, 'z': 2, 'w': 3, 'r': 0, 'g': 1, 'b': 2, 'a': 3}

PROPERTY = [''.join(prod) for prod in product('x', repeat=1)]
PROPERTY += [''.join(prod) for prod in product('r', repeat=1)]
PROPERTY += [''.join(prod) for prod in product('xy', repeat=2)]
PROPERTY += [''.join(prod) for prod in product('rg', repeat=2)]
PROPERTY += [''.join(prod) for prod in product('xyz', repeat=3)]
PROPERTY += [''.join(prod) for prod in product('xyz', repeat=3)]
PROPERTY += [''.join(prod) for prod in product('xyzw', repeat=4)]
PROPERTY += [''.join(prod) for prod in product('rgba', repeat=4)]

class Vec2(np.ndarray):
    __slots__ = [x for x in PROPERTY if len(x) <= 2]

    def __new__(cls, input_array):
        assert len(input_array) == 2
        obj = np.asarray(input_array).view(cls)
        return obj

    def __getattribute__(self, __name: str) -> Any:
        length = len(__name)
        if 1 <= length <= 2 and all([x in 'xyrg' for x in __name]):
            value = [self[TABLE[x]] for x in __name]
            if length == 1:
                return value[0]
            if length == 2:
                return Vec2(value)
        return super().__getattribute__(__name)

class Vec3(np.ndarray):
    __slots__ = [x for x in PROPERTY if len(x) <= 3]

    def __new__(cls, input_array):
        assert len(input_array) == 3
        obj = np.asarray(input_array).view(cls)
        return obj

    def __getattribute__(self, __name: str) -> Any:
        length = len(__name)
        if 1 <= length <= 3 and all([x in 'xyzrgb' for x in __name]):
            value = [self[TABLE[x]] for x in __name]
            if length == 1:
                return value[0]
            if length == 2:
                return Vec2(value)
            if length == 3:
                return Vec3(value)
        return super().__getattribute__(__name)

v = Vec3([3, 2, 1])
v.z

1

In [123]:
import numpy as np
from multipledispatch import dispatch
class Vec3(np.ndarray):
    def __new__(cls, input_array):
        assert len(input_array) == 3
        obj = np.asarray(input_array).view(cls)
        return obj
    
    @dispatch(int)
    def foo(self, a):
        print('foo')
    @dispatch(float)
    def foo(self, a):
        print('bar')

Vec3([3, 2, 1]).foo(3.2)

bar


In [121]:
class SampleC(np.ndarray):
    @dispatch(int,int)
    def product(x, y):
        return x * y
    
    @dispatch(int,int,int)
    def product(x, y ,z):
        return x * y * z

    @dispatch(float,float)
    def product(x, y):
        return x * y

c = SampleC(3)

# 정수 파라미터 두개
print('ex 3 > ',c.product(2, 3))
# 정수 파라미터 세개
print('ex 3 > ',c.product(2, 3, 4))
# 실수 파라미터 두개
print('ex 3 > ',c.product(2.0, 3.0))

ex 3 >  6
ex 3 >  24
ex 3 >  6.0


In [95]:
import numpy as np

class MySubClass(np.ndarray):

    def __new__(cls, input_array, info=None):
        obj = np.asarray(input_array).view(cls)
        obj.info = info
        return obj

    def __array_finalize__(self, obj):
        print('In __array_finalize__:')
        print('   self is %s' % repr(self))
        print('   obj is %s' % repr(obj))
        if obj is None: return
        self.info = getattr(obj, 'info', None)

    def __array_wrap__(self, out_arr, context=None):
        print('In __array_wrap__:')
        print('   self is %s' % repr(self))
        print('   arr is %s' % repr(out_arr))
        # then just call the parent
        return super().__array_wrap__(self, out_arr, context)

In [48]:
np.array([3, 2]).any()

True